"""add filename column

Revision ID: 595590b37fee
Revises: d9a53a28ba54
Create Date: 2025-07-30 09:53:39.635807

"""

# revision identifiers, used by Alembic.
revision = '595590b37fee'
down_revision = 'd9a53a28ba54'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.UnicodeText(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
